/**
 * Shared types for the evaluator package.
 * These will eventually move to @harnessfit/core when that package is built out.
 */

/** The result of running a benchmark task against a generated patch. */
export interface RunResult {
  /** The patch generated by the agent (unified diff format). */
  readonly patch: string;
  /** Exit code from the agent process. */
  readonly exitCode: number;
  /** Files modified by the patch (relative paths). */
  readonly changedFiles: readonly string[];
  /** Wall-clock duration in milliseconds. */
  readonly durationMs: number;
}

/** The decomposed score for a task run. */
export interface TaskScore {
  /** 0.70 weight — did hidden acceptance tests pass? (0.0–1.0) */
  readonly functional: number;
  /** 0.10 weight — do existing tests, typecheck, and lint still pass? (0.0–1.0) */
  readonly regression: number;
  /** 0.10 weight — were constraints violated? (0.0–1.0, penalty for violations) */
  readonly constraint: number;
  /** 0.10 weight — is the patch of reasonable quality? (0.0–1.0) */
  readonly quality: number;
  /** Weighted total: 0.70×functional + 0.10×regression + 0.10×constraint + 0.10×quality */
  readonly total: number;
  /** Individual test results for transparency. */
  readonly details: ScoreDetails;
}

export interface ScoreDetails {
  readonly functionalTestsPassed: number;
  readonly functionalTestsTotal: number;
  readonly regressionTestsPassed: number;
  readonly regressionTestsTotal: number;
  readonly typecheckPassed: boolean;
  readonly lintPassed: boolean;
  readonly constraintViolations: readonly string[];
  readonly patchLineCount: number;
  readonly newDuplicationDetected: boolean;
  readonly newLintViolations: number;
}
